debug: true
server:
  user_address: ":9567"
  user_address_http: ":9568"
  article_address: "localhost:8567"
database:
  host: localhost
  port: 5432
  user: 
  pass: 
  name: 
queue:
  host: localhost
  port: 6379
  pass:
  username:
  dial: "amqps://notification:notification123@b-bc213140-45a3-4522-8bb1-6e8156c0af68.mq.ap-southeast-3.amazonaws.com:5671"

