debug: true
server:
  user_address: ":9567"
  user_address_http: ":9568"
  article_address: "localhost:8567"
database:
  host: localhost
  port: 5432
  user: 
  pass: 
  name: 
queue:
  host: localhost
  port: 6379
  pass:
  username:
  dial: "amqps://siquinxc:29OzHKEFqBOrmxA8z6IRIMUewXXiAAaf@fly.rmq.cloudamqp.com/siquinxc"
email:
  host: smtp.gmail.com
  port: 587
  emailkey: ""
  password: ""
  address_mail: ""
  from_name_email: ""