debug: true
server:
  user_address: ":9567"
  user_address_http: ":9568"
  article_address: "localhost:8567"
database:
  host: 156.67.213.192
  port: 3306
  user: u5364860_vianto_fajrul
  password: fajrul2022!
  dbName: u5364860_fajrulislam_dev 
queue:
  host: localhost
  port: 6379
  pass:
  username:
  dial: "amqps://siquinxc:29OzHKEFqBOrmxA8z6IRIMUewXXiAAaf@fly.rmq.cloudamqp.com/siquinxc"
email:
  host: mail.fajrulislam.or.id
  port: 465
  email: no-reply@fajrulislam.or.id
  password: adminfajrul12345678
  address_mail: mail.fajrulislam.or.id:587
  from_name_email: "Fajrul Islam Gunadarma <no-reply@fajrulislam.or.id>"
# email:
#   host: mail.kemkes.go.id
#   port: 587
#   email: mhealth@kemkes.go.id
#   password: Mh34lth.,,
#   address_mail: mail.kemkes.go.id:587
#   from_name_email: "Kementerian Kesehatan Republik Indonesia <mhealth@kemkes.go.id>"